server:
  error:
    include-messages: always
    include-binding-errors: always
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/db_aps_snapshot
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

springdoc:
  swagger-ui:
    path: /api-docs

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    format-sql: true