version: '3.9'
services:
  mysql:
    image: mysql:9.2
    container_name: mysql_aps2
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_aps2
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-scripts:/docker-entrypoint-initdb.d 
      - mysql_data:/var/lib/mysql 
    networks:
      - springboot-network

  # service-events:
  #   build:
  #     context: ./services/event-management-service 
  #   container_name: event-management-service
  #   ports:
  #     - "8081:8081" 
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/db_aps2
  #     SPRING_DATASOURCE_USERNAME: root
  #     SPRING_DATASOURCE_PASSWORD: 123456
  #   networks:
  #     - springboot-network
  #   depends_on:
  #     - mysql

  # service-tickets:
  #   build:
  #     context: ./services/service-tickets # Caminho do serviço de ingressos
  #   container_name: service-tickets
  #   ports:
  #     - "8082:8082" # Porta para acessar o serviço
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/event_management
  #     SPRING_DATASOURCE_USERNAME: user
  #     SPRING_DATASOURCE_PASSWORD: password
  #   networks:
  #     - springboot-network
  #   depends_on:
  #     - mysql

  # frontend:
  #   build:
  #     context: ./frontend # Caminho do projeto frontend
  #   container_name: frontend
  #   ports:
  #     - "3000:3000" # Porta para acessar o frontend
  #   networks:
  #     - springboot-network

volumes:
  mysql_data: # Volume para persistir os dados do banco de dados

networks:
  springboot-network: # Rede compartilhada para comunicação entre os serviços
