version: '3.9'
services:
  mysql-aps2:
    image: mysql:9.2
    container_name: mysql_aps2
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_aps2
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-scripts:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - aplicacao-venda-ingressos
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=123456"]
      interval: 10s
      retries: 5
      timeout: 5s

  rabbit-mq-aps2:
    image: rabbitmq:management
    container_name: rabbit-mq_aps2
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - aplicacao-venda-ingressos
    depends_on:
      mysql-aps2:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      timeout: 5s

  service-user:
    build:
      context: ./services/user-service
    container_name: user-service
    ports:
      - "8084:8084"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-aps2:3306/db_aps2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456

    networks:
      - aplicacao-venda-ingressos
    depends_on:
      mysql-aps2:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8084/actuator/health || exit 1"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  service-events:
    build:
      context: ./services/event-management-service
    container_name: event-management-service
    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-aps2:3306/db_aps2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_RABBITMQ_HOST: rabbit-mq-aps2
      SPRING_RABBITMQ_PORT: 5672

    networks:
      - aplicacao-venda-ingressos
    depends_on:
      service-user:
        condition: service_healthy
      rabbit-mq-aps2:
        condition: service_healthy
      mysql-aps2:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -u admin:teste123 -f http://localhost:8080/api/actuator/health || exit 1"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  service-tickets:
    build:
      context: ./services/ticket-service
    container_name: tickets-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-aps2:3306/db_aps2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_RABBITMQ_HOST: rabbit-mq-aps2
      SPRING_RABBITMQ_PORT: 5672
    networks:
      - aplicacao-venda-ingressos
    depends_on:
      service-events:
        condition: service_healthy
      service-user:
        condition: service_healthy  
      rabbit-mq-aps2:
        condition: service_healthy
      mysql-aps2:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

volumes:
  mysql_data:

networks:
  aplicacao-venda-ingressos:
