spring:
  application:
    name: event-management-service

  security:
    basic:
      enable: false

  datasource:
    url: jdbc:mysql://localhost:3307/db_aps2
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    format-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#  sql:
#    init:
#      platform: mysql                                        # Plataforma para inicialização do banco
#      mode: always                                           # Executa scripts SQL ao inicializar

server:
  port: 8080
  servlet.context-path: /api

logging:
  level:
    root: info                                               # Nível de log padrão
#    org.hibernate.SQL: debug                                 # Mostra as queries SQL
#    org.hibernate.type.descriptor.sql: trace                 # Mostra parâmetros das queries SQL
  file.name: logs/application.log
  file.path: logs

management:
  endpoints:
    web:
      exposure:
        include: '*'                                         # Expõe todos os endpoints do actuator
  endpoint:
    health:
      show-details: always                                   # Exibe detalhes nos relatórios de saúde

