services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_aps_snapshot
    container_name: mysql
    image: mysql:9.2
    volumes:
      - mysql_volume_snapshot:/var/lib/mysql
    ports:
      - 3308:3306
    networks:
      - mysql_network

volumes:
  mysql_volume_snapshot:

networks:
  mysql_network: